docblockfail.lo: /Users/paulscoder/personalrepos/docblockfail/ext/docblockfail.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/docblockfail.c -o docblockfail.lo 
kernel/main.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /Users/paulscoder/personalrepos/docblockfail/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/kernel/exit.c -o kernel/exit.lo 
docblockfail/docblocktest.lo: /Users/paulscoder/personalrepos/docblockfail/ext/docblockfail/docblocktest.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/paulscoder/personalrepos/docblockfail/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/paulscoder/personalrepos/docblockfail/ext/docblockfail/docblocktest.zep.c -o docblockfail/docblocktest.lo 
$(phplibdir)/docblockfail.la: ./docblockfail.la
	$(LIBTOOL) --mode=install cp ./docblockfail.la $(phplibdir)

./docblockfail.la: $(shared_objects_docblockfail) $(DOCBLOCKFAIL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_docblockfail) $(DOCBLOCKFAIL_SHARED_LIBADD)

